Changes to implementation and test of iaf_psc_exp_ps_lossless for Nest PR #901
heplesser/nest-simulator pull request #22
Opened 2018-03-30 15:36 UTC by ChristianKeup

Resolves the problem I found in the spike detection algorithm and fixes the existing test.
The extension of the test to look at the region of missed spikes will follow after Easter.
For general comments please see Nest PR #901

2018-04-03 11:50 UTC, heplesser requested changes
@ChristianKeup Thanks for fixing this, and yes, you created the PR in the correct way. I just found one small point to improve, see inline comments. Furthermore, the static code checker is unhappy about some lines in iaf_psc_exp_ps_lossless.cpp. Could you run `extras/check_code_style.sh` in your source directory and fix the errors indicated (using `clang-format-3.6 -i ...`?

2018-04-03 11:50 UTC, heplesser commented on precise/iaf_psc_exp_ps_lossless.cpp
> +  double f =
@ChristianKeup Make this `const double`, since `f` does not change below. This allows the compiler to generate more optimal code.

2018-04-05 15:26 UTC, ChristianKeup commented
During checking the spike detection algorithm, I found that while the model allows to set two different time constants for exc. and inh. synapses, the spike detection rests on the assumption that the two time constants are equal.
Extending the algorithm would be quite some work, since the neurons state space is then 3 dimensional ('V_m_', 'I_syn_ex_' and 'I_syn_in_').

Therefore, should I build in a check that simply forbids the user to set different synaptic time constants, or should  I completely replace 'tau_ex_' and 'tau_in_' by a single parameter 'tau_syn' ?

2018-04-05 20:12 UTC, heplesser commented
@ChristianKeup Good catch!  I would suggest that you add a test that enforces tau_ex == tau_in, and add a note in the documentation. In this way, we can later modify the model to support tau_ex != tau_in without any change to the user interface. Maybe you could create a follow-up issue for that.

2018-04-07 12:32 UTC, heplesser approved these changes

2018-04-07 12:37 UTC, heplesser commented
@ChristianKeup Travis is now failing due to an old test. I merge your PR here and will fix the test myself.

2018-04-07 12:37 UTC, merged